# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monad < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bkeane/monad/releases/download/0.0.1/monad_Darwin_x86_64.tar.gz"
      sha256 "92e480b44247c1960464d83eb8c1557be5c929ffbbee3e63dfa6c880362a43c2"

      def install
        bin.install "monad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bkeane/monad/releases/download/0.0.1/monad_Darwin_arm64.tar.gz"
      sha256 "023504692cd4a467dceb4bfc617ffd414609b33a9aa8ef9679c73f67639b5b4a"

      def install
        bin.install "monad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bkeane/monad/releases/download/0.0.1/monad_Linux_x86_64.tar.gz"
        sha256 "77b088e8a2df28044d228a4f6b6e1ccc846db0226e80a4c7c58ce34490712fdc"

        def install
          bin.install "monad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bkeane/monad/releases/download/0.0.1/monad_Linux_arm64.tar.gz"
        sha256 "dbe4231af91499a5c19c8e9dc40a533db596202555907f1493c1f1c9b0c79af5"

        def install
          bin.install "monad"
        end
      end
    end
  end
end
