# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Substrate < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bkeane/substrate/releases/download/0.0.1/substrate_Darwin_x86_64.tar.gz"
      sha256 "e3cc55d35983c815a9790d17fe90487f459d984e13fe5c641720e8180d13e426"

      def install
        bin.install "substrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bkeane/substrate/releases/download/0.0.1/substrate_Darwin_arm64.tar.gz"
      sha256 "09cbdf7778245eb1dbdac60cfe4d2dbee87469b66af4d733f3072be2f1e28ef5"

      def install
        bin.install "substrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bkeane/substrate/releases/download/0.0.1/substrate_Linux_x86_64.tar.gz"
        sha256 "d10c78cb8a10e0b1103d808ce3058466f367969bbd041b011e93e982d61e4d72"

        def install
          bin.install "substrate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bkeane/substrate/releases/download/0.0.1/substrate_Linux_arm64.tar.gz"
        sha256 "365417d3c6207ef1e0abbe287f26c6ccd1b1c353fe42b3c1abdd5c2838fe7e7e"

        def install
          bin.install "substrate"
        end
      end
    end
  end
end
